name: Linting

on:
  pull_request:
    branches-ignore: [master, main]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Styling Tools
        run: python -m pip install isort black flake8 pylint
      - name: Run linters
        run: |
          isort countrycode --check
          black countrycode --check
          pylint countrycode