name: Linting

on:
  pull_request:
    branches-ignore: [master, main]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
      - name: Install deps
        run: |
          poetry install --with=dev
      - name: Run linters
        run: |
          poetry run black countrycode --check
          poetry run pylint countrycode