name: CI Testing

on:
  push:
    pull_request:

    workflow_dispatch:

jobs:
  testing:
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: snok/install-poetry@v1

      - name: Install deps
        run: |
          poetry install --with=dev

      - name: Run tests
        run: |
          pytest

      - name: Dummy echo
        run: |
          echo "in action"