name: CI Testing

on:
  push:
    pull_request:
    workflow_dispatch:
    workflow_call:

jobs:
  linting-check:
    uses: ./.github/workflows/lint.yml
  testing:
    needs: linting-check
    strategy:
      fail-fast: true
      matrix:
        python:
          - "3.9"
          - "3.10"
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
      - name: List directory
        run: |
          ls -a
      - name: Install deps
        run: |
          poetry install --with=dev
      - name: Run tests on ${{matrix.os }}
        run: |
          pytest
