name: CI Testing

on:
  push:
    pull_request:

    workflow_dispatch:

jobs:
  testing:
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
        os: ["ubuntu-latest", "macos-latest", "windows-2022"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
      - name: Install deps
        run: |
          poetry install --with=dev
      - name: Run tests on ${{matrix.os }}
        run: |
          source .venv/bin/activate
          pytest
